version: '3.4'




services:
  rabbitmq: 
    image:  rabbitmq:3.10-management
    ports: 
      - "5672:5672"
      - "15672:15672" 

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
    depends_on:
      - rabbitmq

  orders.api:
    image: ${DOCKER_REGISTRY-}ordersapi
    build:
      context: .
      dockerfile: Orders.API/Dockerfile
    depends_on:
      - rabbitmq


